repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Frontend hooks
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.52.0
        -   eslint-config-prettier@9.0.0
        -   eslint-plugin-prettier@5.0.1
        -   eslint-plugin-react@7.33.2
        -   eslint-plugin-react-hooks@4.6.0
        -   @typescript-eslint/eslint-plugin@6.9.1
        -   @typescript-eslint/parser@6.9.1

# Backend hooks
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        files: \.py$

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        language_version: python3.9
        files: \.py$

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        files: \.py$
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        files: \.py$
        additional_dependencies:
        -   pydantic==1.10.8
        -   sqlalchemy==2.0.19
        -   types-requests
