# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:admin@123@db/hr_ai
      - OPENAI_API_KEY=${OPENAI_KEY}

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: hr_ai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql_data: